//
//  PrivacyPolicy.swift
//  
//
//  Created by Martin Poulsen on 2021-08-17.
//

import SwiftUI

struct PrivacyPolicy: View {
    @EnvironmentObject var authVM: AuthViewModel
    @Environment(\.dismiss) private var dismiss
    @Environment(\.colorScheme) var colorScheme
    
    var body: some View {
        NavigationView {
            ZStack {
                Color.accentColor
                    .opacity(colorScheme == .light ? authVM.opacityLightMode : authVM.opacityDarkMode)
                    .ignoresSafeArea()
                VStack {
                    Text("Privacy Policy", comment: "Header")
                        .fontWeight(.light)
                        .font(.title)
                        .foregroundColor(.secondary)
                        .padding()
                    Text("No personal information is collected in our app. We do not store your information because we respect your privacy. Game data generated by users is automatically deleted after 1 to 3 days, this applies to drawing pads with associated images.", comment: "Body Privacy Policy")
                        .lineSpacing(5)
                    Spacer()
                }
                .frame(maxWidth: 500)
                .padding()
            }
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button {
                        dismiss()
                    } label: {
                        Image(systemName: "xmark.circle")
                    }
                }
            }
        }
        .navigationViewStyle(.stack)
    }
}

struct PrivacyPolicy_Previews: PreviewProvider {
    static var previews: some View {
        PrivacyPolicy()
            .environmentObject(AuthViewModel())
    }
}
